# Generated by Django 3.2.7 on 2021-10-02 09:13

from django.db import migrations, models
import django.db.models.deletion
import statement.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0006_customer_makhachhang'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=statement.models.current_year)),
                ('open_date', models.DateField(auto_now_add=True)),
                ('close_date', models.DateField(blank=True, null=True)),
                ('is_close', models.BooleanField(default=False)),
                ('open_debit', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True)),
                ('open_credit', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True)),
                ('in_debit', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True)),
                ('in_credit', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True)),
                ('close_debit', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True)),
                ('close_credit', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='customers.customer')),
            ],
        ),
    ]
