# Generated by Django 3.2.7 on 2021-10-02 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customer_makhachhang'),
        ('statement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='close_credit',
        ),
        migrations.RemoveField(
            model_name='period',
            name='close_debit',
        ),
        migrations.RemoveField(
            model_name='period',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='period',
            name='in_credit',
        ),
        migrations.RemoveField(
            model_name='period',
            name='in_debit',
        ),
        migrations.RemoveField(
            model_name='period',
            name='open_credit',
        ),
        migrations.RemoveField(
            model_name='period',
            name='open_debit',
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_debit', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True)),
                ('open_credit', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True)),
                ('transaction_debit', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True)),
                ('transaction_credit', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True)),
                ('close_debit', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True)),
                ('close_credit', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='customers.customer')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stament', to='statement.period')),
            ],
        ),
    ]
