# Generated by Django 3.2.7 on 2021-10-06 08:14

from django.db import migrations, models
import statement.models


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='month',
            field=models.IntegerField(default=statement.models.current_month),
        ),
    ]
