# Generated by Django 3.2.7 on 2021-10-02 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('statement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Loại hàng hóa')),
                ('unit', models.CharField(max_length=10, verbose_name='Đơn vị tính')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('VND', 'VND')], default='USD', max_length=3)),
                ('date_sent', models.DateTimeField()),
                ('date_flight', models.DateTimeField(blank=True, null=True)),
                ('date_received', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='customers.customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='orders.item')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statement.period')),
            ],
        ),
    ]
