# Generated by Django 3.2.7 on 2021-10-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20211007_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_sent',
            field=models.DateTimeField(),
        ),
    ]
