# Generated by Django 3.2.7 on 2021-10-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_date_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_sent',
            field=models.DateField(),
        ),
    ]
