# Generated by Django 3.2.7 on 2021-10-02 16:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='API_KEY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_link', models.CharField(max_length=255)),
                ('api_key', models.CharField(max_length=124)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=30)),
                ('phone_number', models.CharField(default='', max_length=12)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('TIN', models.CharField(max_length=13, unique=True, verbose_name='Mã số thuế')),
                ('DOB', models.DateField(blank=True, null=True, verbose_name='Ngày Sinh')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('makhachhang', models.CharField(default='131', max_length=5)),
                ('last_transaction', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
    ]
