# Generated by Django 3.2.7 on 2021-10-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='api_key',
            name='title',
            field=models.CharField(default='', max_length=20),
        ),
    ]
