# Generated by Django 3.2.7 on 2021-09-29 13:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20210929_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='last_transaction',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
