# Generated by Django 3.2.7 on 2021-10-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_last_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='API_KEY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_link', models.CharField(max_length=255)),
                ('api_key', models.CharField(max_length=124)),
            ],
        ),
    ]
