# Generated by Django 3.2.7 on 2021-10-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customertransaction_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='TIN',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='Mã số thuế'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='makhachhang',
            field=models.CharField(blank=True, default='131', max_length=5, null=True),
        ),
    ]
