# Generated by Django 3.2.7 on 2021-10-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20211015_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='TIN',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
