# Generated by Django 3.2.7 on 2021-10-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customertransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='makhachhang',
            field=models.CharField(default='131', max_length=5),
        ),
    ]
