# Generated by Django 3.2.7 on 2021-10-02 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='period',
        ),
    ]
