# Generated by Django 3.2.7 on 2021-10-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_currencyrates_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrates',
            name='rate',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
    ]
