# Generated by Django 3.2.7 on 2021-10-01 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_total_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='total_amount',
            new_name='needed_paid',
        ),
    ]
