# Generated by Django 3.2.7 on 2021-10-02 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_api_key'),
        ('orders', '0007_alter_order_currency'),
        ('payments', '0005_rename_total_amount_payment_needed_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phatsinh_no', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('phatsinh_co', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trans', to='customers.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trans', to='orders.order')),
            ],
        ),
    ]
