# Generated by Django 3.2.7 on 2021-10-02 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_auto_20211002_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='phatsinh_co',
            new_name='must_paid',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='order',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='phatsinh_no',
        ),
    ]
